language: c
sudo: false
notifications: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - mkdir -p $HOME/arduino_ide/libraries/
  - cd $HOME/arduino_ide/libraries/
  - git clone --branch 2.1.4 https://github.com/Makuna/NeoPixelBus.git
  - git clone https://github.com/interactive-matter/aJson.git
  - sed -i -e 's|#define PRINT_BUFFER_LEN 256|#define PRINT_BUFFER_LEN 4096|g'  aJson/aJSON.h
  - cd -
script:
  - sed -i -e 's|#include "/secrets.h"|//#include "/secrets.h"|g' ESP8266HueEmulator/ESP8266HueEmulator.ino
  - sed -i -e 's|//const char|const char|g' ESP8266HueEmulator/ESP8266HueEmulator.ino
  - build_platform esp8266
